# custom binds
unbind C-b
set -g prefix C-f

unbind r
bind r source-file ~/.tmux.conf

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

####
set -g mouse on
setw -g mode-keys vi
set-option -g set-titles on

set -g status on
set -g status-position top
set -g status-interval 2
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=white,bg=#1c1c24"
# set -g status-justify absolute-centre
set -g message-style "fg=black,bg=cyan"
set -g status-left "#[fg=black,bg=cyan]  #H #[fg=white,bg=black]  #S #{prefix_highlight}"
set -g status-right " #[fg=white,bg=black] 󰃭 %A %d %b #[fg=black,bg=cyan] 󰥔 %I:%M:%S %p "
setw -g window-status-separator " "
setw -g window-status-format '#[fg=black,bg=#aaaaaa] #I #[bg=black,fg=#aaaaaa] #(basename "#{pane_current_path}")'
setw -g window-status-current-format '#[fg=black,bg=yellow] #I #[fg=white,bg=black] #(basename "#{pane_current_path}")'

# plugins
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"

set -g @plugin 'jaclu/tmux-menus'
set -g @menus_trigger 'Space'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
# set -g @continuum-save-interval '10'

###
run '~/.tmux/plugins/tpm/tpm'

